import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../css/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-14 border-b">
          <div className="mx-auto flex w-full max-w-[1440px] items-center justify-between px-8">
            Header
          </div>
        </div>
        {children}
      </body>
    </html>
  )
}
