import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../css/globals.css'
import Image from 'next/image'
import { HeroOverlay } from '@/components/hero-overlay'
import { Header } from '@/components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative min-h-screen w-full overflow-y-auto`}>
        <Header />
        <div className="pt-14">
          {children}
          <HeroOverlay />
        </div>
      </body>
    </html>
  )
}
